spring:
  # DataSource
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=FinalProject;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
  
  # SessionFactory
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
   
  # i18n
  messages:
    basename: i18n.Messages
    encoding: UTF-8
    fallback-to-system-locale: false

  # ViewResolver
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  profiles:
    active: '@xxx@'
 
server:
  port: 8080
  